# -*- coding: utf-8 -*-
"""module 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qP6Jh3bpX4Z5Nju8QcLUizM9FULGmnBe
"""

input1, input2 = int(input("Enter a number ")), int(input("Enter a number "))
print(input1 , "+", input2, "= ", (input1+input2) )
print(input1 , "-", input2, "= ", (input1-input2) )

input1, input2 = int(input("Enter a number ")), int(input("Enter a number "))
print(input1 , "*", input2, "= ", (input1*input2) )
print(input1 , "/", input2, "= ", (input1/input2) )